In [1]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

ordinary_list = array.tolist()

print(ordinary_list)

[1, 2, 3, 4, 5]


In [2]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Manually (without direct function)

sum_diagonal = 0
for i in range(array.shape[0]):
    sum_diagonal += array[i, i]

print("Method 1: Sum of the diagonal elements:", sum_diagonal)

# Using the trace function
sum_diagonal = np.trace(array)

print("Method 2: Sum of the diagonal elements:", sum_diagonal)

Method 1: Sum of the diagonal elements: 15
Method 2: Sum of the diagonal elements: 15


In [3]:
import numpy as np

array = np.array([[1, 2], [3, 5]])

X = 2

result = array[array > X]

print(result)

[3 5]


In [4]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

C = np.empty(A.shape)

for i in range(A.shape[0]):
    C[i] = A[i] + B[i]

print(C)


[5. 7. 9.]


In [5]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

row_means = np.mean(matrix, axis=1, keepdims=True)

result = matrix - row_means

print(result)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
